matrix:
  include:
    - language: python
      python:
        - "3.7"
      before_install:
        - pwd
        - cd python
        - pwd
        - python --version
        - pip install -U pip
        - pip install -U pytest
      install:
        - pip install -r requirements.txt
      before_script:
        - cd python
      script: pytest