matrix:
  include:
    - language: python
      python:
        - "3.7"
      before_install:
        - python --version
        - pip install -U pip
        - pip install -U pytest
      before_script:
        - cd python
      script: pytest