matrix:
  include:
    - language: python
      python:
        - "3.7"
      before_install:
        - cd python
        - python --version
        - pip install -U pip
        - pip install -U pytest
        - pip install -U pylint
      install:
        - pip install -r requirements.txt
      script:
        - python3 -m pylint *.py